theme: minima
title: Vietnam balloons go programming!
author: GitHub User
email: booking@vietnamballoons.com
description: > # this means to ignore newlines until "baseurl:"
  VietnamBalloons.com is a site to order balloon flights.

# social links
twitter_username: TVLith # DO NOT include the @ character, or else the build will fail!
github_username:  freetrade7 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
